import '../styles/globals.css';

export const metadata = {
  title: 'ChatGPT Messenger',
  description: 'Generated by Digi-Angler',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
